//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public int Id_Articulo { get; set; }
        public string Descripcion { get; set; }
        public int Id_TipoInventario { get; set; }
        public string Unidad { get; set; }
        public int Existencia { get; set; }
        public int Num_Referencia { get; set; }
        public decimal Costo_Unitario { get; set; }
        public string Estado { get; set; }
        public string Marca { get; set; }
    }
}
