//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulo()
        {
            this.Transaccions = new HashSet<Transaccion>();
        }
    
        public int Id_Articulo { get; set; }
        public string Descripcion { get; set; }
        public int Id_TipoInventario { get; set; }
        public string Unidad { get; set; }
        public int Existencia { get; set; }
        public int Num_Referencia { get; set; }
        public decimal Costo_Unitario { get; set; }
        public string Estado { get; set; }
        public string Marca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccions { get; set; }
        public virtual TipoInventario TipoInventario { get; set; }
    }
}
