//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsientosContable
    {
        public int Id_AsientosContables { get; set; }
        public string descripcion { get; set; }
        public int Id_TipoInventario { get; set; }
        public int cuentaContable { get; set; }
        public string Tipo_de_Movimiento { get; set; }
        public System.DateTime Fecha_Asiento { get; set; }
        public decimal Monto_Asiento { get; set; }
        public string Estado { get; set; }
        public Nullable<int> AsientoContabilidad_ID { get; set; }
    
        public virtual TipoInventario TipoInventario { get; set; }
    }
}
