//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsientosContable
    {
        public int Id_AsientosContables { get; set; }
        public string descripcion { get; set; }
        public int Id_TipoInventario { get; set; }
        public int cuentaContable { get; set; }
        public string Tipo_de_Movimiento { get; set; }
        public System.DateTime Fecha_Asiento { get; set; }
        public decimal Monto_Asiento { get; set; }
        public string Estado { get; set; }
    
        public virtual TipoInventario TipoInventario { get; set; }
    }
}
