//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoInventario
    {
        public int Id_TipoInventario { get; set; }
        public string Descripcion { get; set; }
        public int CuentaContable { get; set; }
        public string Estado { get; set; }
    }
}
