//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoInventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoInventario()
        {
            this.AsientosContables = new HashSet<AsientosContable>();
        }
    
        public int Id_TipoInventario { get; set; }
        public string Descripcion { get; set; }
        public int CuentaContable { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsientosContable> AsientosContables { get; set; }
        public virtual ICollection<Articulo> Articuloes { get; set; }
    }
}
